### ISSUE TITLE
Spark Startup error/warning

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#12]
Every time Spark starts, the error below is printed out in the logs. It doesn't not affect the results, and Spark still works, but I think this looks bad to the testers. @quintinali  didn't find a way to fix it, @lewismc can you help take a look.

I am testing the new code right now, and should be able to get back to you by the end of Monday.

2016-07-24 19:37:08,322 WARN org.spark-project.jetty.util.component.AbstractLifeCycle: FAILED SelectChannelConnector@0.0.0.0:4040: java.net.BindException: Address already in use: bind
java.net.BindException: Address already in use: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
    at org.spark-project.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:187)
    at org.spark-project.jetty.server.AbstractConnector.doStart(AbstractConnector.java:316)
    at org.spark-project.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:265)
    at org.spark-project.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.spark-project.jetty.server.Server.doStart(Server.java:293)
    at org.spark-project.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
    at org.apache.spark.ui.JettyUtils$.org$apache$spark$ui$JettyUtils$$connect$1(JettyUtils.scala:228)
    at org.apache.spark.ui.JettyUtils$$anonfun$2.apply(JettyUtils.scala:238)
    at org.apache.spark.ui.JettyUtils$$anonfun$2.apply(JettyUtils.scala:238)
    at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1991)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
    at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1982)
    at org.apache.spark.ui.JettyUtils$.startJettyServer(JettyUtils.scala:238)
    at org.apache.spark.ui.WebUI.bind(WebUI.scala:117)
    at org.apache.spark.SparkContext$$anonfun$13.apply(SparkContext.scala:448)
    at org.apache.spark.SparkContext$$anonfun$13.apply(SparkContext.scala:448)
    at scala.Option.foreach(Option.scala:236)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:448)
    at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:61)
    at esiptestbed.mudrod.driver.SparkDriver.<init>(SparkDriver.java:31)
    at esiptestbed.mudrod.main.MudrodEngine.<init>(MudrodEngine.java:48)
    at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:122)

**Comment by lewismc** [comment]
This has to do with your local environment.
Please consult
https://support.datastax.com/hc/en-us/articles/207356773-FAQ-Warning-message-java-net-BindException-Address-already-in-use-when-launching-Spark-shell
Let me know if you resolve it.

**Comment by lewismc** [comment]
@Yongyao PING is this still an issue? If not then please resolve.
