### ISSUE TITLE
Can't create new threads during log ingestion

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#126]
While trying to run a full log ingestion locally, I received the following error:

```
2017-03-30 14:44:26,693 INFO  rdd.EsRDDWriter (RestService.java:createWriter(562)) - Writing to [podaaclog201611.gz/rawhttp]
2017-03-30 14:53:04,620 INFO  rdd.EsRDDWriter (RestService.java:createWriter(562)) - Writing to [podaaclog201611.gz/rawftp]
2017-03-30 14:56:10,734 INFO  pre.ImportLogFile (ImportLogFile.java:execute(78)) - Log Import complete. Time elapsed 705 seconds
2017-03-30 14:56:10,741 INFO  pre.CrawlerDetection (CrawlerDetection.java:execute(93)) - Starting Crawler detection rawhttp.
2017-03-30 14:56:13,047 INFO  pre.CrawlerDetection (CrawlerDetection.java:checkByRateInParallel(159)) - Original User count: 6365
[Stage 5:=======================================>                 (67 + 4) / 96]15:01:19.533 [elasticsearch[_client_][transport_client_worker][T#2]{New I/O worker #1192}] ERROR org.elasticsearch.transport.netty3.Netty3Utils - fatal error on the network layer
	at org.elasticsearch.transport.netty3.Netty3Utils.maybeDie(Netty3Utils.java:195)
	at org.elasticsearch.transport.netty3.Netty3MessageChannelHandler.exceptionCaught(Netty3MessageChannelHandler.java:82)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.exceptionCaught(FrameDecoder.java:377)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:112)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:525)
	at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:48)
	at org.jboss.netty.channel.DefaultChannelPipeline.notifyHandlerException(DefaultChannelPipeline.java:658)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:566)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-03-30 15:01:19,556 ERROR executor.Executor (Logging.scala:logError(91)) - Exception in task 70.0 in stage 5.0 (TID 172)
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at org.elasticsearch.threadpool.ThreadPool.<init>(ThreadPool.java:217)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:127)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:258)
	at gov.nasa.jpl.mudrod.utils.ESTransportClient.<init>(ESTransportClient.java:46)
	at gov.nasa.jpl.mudrod.utils.ESTransportClient.<init>(ESTransportClient.java:42)
	at gov.nasa.jpl.mudrod.driver.ESDriver.makeClient(ESDriver.java:423)
	at gov.nasa.jpl.mudrod.driver.ESDriver.<init>(ESDriver.java:98)
	at gov.nasa.jpl.mudrod.weblog.pre.CrawlerDetection$2.call(CrawlerDetection.java:166)
	at gov.nasa.jpl.mudrod.weblog.pre.CrawlerDetection$2.call(CrawlerDetection.java:162)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:796)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fgreg** [comment]
The cause of the problem is in this code:

https://github.com/mudrod/mudrod/blob/2c44ea427052e14fbab53891580da6296e3d00b4/core/src/main/java/gov/nasa/jpl/mudrod/weblog/pre/CrawlerDetection.java#L166-L175
```
        ESDriver tmpES = new ESDriver(props);
        tmpES.createBulkProcessor();
        List<Integer> realUserNums = new ArrayList<Integer>();
        while (arg0.hasNext()) {
          String s = arg0.next();
          Integer realUser = checkByRate(tmpES, s);
          realUserNums.add(realUser);
        }
        tmpES.destroyBulkProcessor();
        return realUserNums.iterator();
```

As we can see a new `ESDriver` is created which in turn creates a new `TransportClient` which essentially opens new connections to Elastic Search.

The problem is that `ESDriver` (and in turn `TransportClient`) is never closed; and so we have a thread leak.

It is fixed by adding `tmpES.close();` after `tmpES.destroyBulkProcessor();`

**Comment by fgreg** [comment]
After further analysis there are 6 methods in total which suffer from this same bug:

- gov.nasa.jpl.mudrod.weblog.pre
  - CrawlerDetection.java
    - checkByRateInParallel()
  - SessionGenerator.java
    - combineShortSessionsInParallel(int)
    - genSessionByRefererInParallel(int)
  - SessionStatistic.java
    - processSessionInParallel()
- gov.nasa.jpl.mudrod.weblog.structure
  - SessionExtractor.java
    - extractRankingTrainDataInParallel(Properties, SparkDriver, ESDriver)
    - getClickStreamListInParallel(Properties, SparkDriver, ESDriver)

**Comment by fgreg** [comment]
I've fixed the code; just running a test to make sure this actually resolves the problem.

**Comment by fgreg** [comment]
Tests worked, merged to master.
