### ISSUE TITLE
Field [Dataset-Metadata] is not a completion suggest field

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#128]
Getting error `Field [Dataset-Metadata] is not a completion suggest field` on mudrod.jpl.nasa.gov site.

```
2017-04-11 20:06:04,565 ERROR interceptor.AbstractFaultChainInitiatorObserver - Error occurred during error handling, give up!
org.apache.cxf.interceptor.Fault: all shards failed
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:162)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:128)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:254)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:223)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:274)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Failed to execute phase [query], all shards failed; shardFailures {[a64iSYrdS8C4ZA1ah0Hb6A][mudrod][0]: RemoteTransportException[[mudrod-server][192.168.173.35:9300][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[Field [Dataset-Metadata] is not a completion suggest field]; }{[a64iSYrdS8C4ZA1ah0Hb6A][mudrod][1]: RemoteTransportException[[mudrod-server][192.168.173.35:9300][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[Field [Dataset-Metadata] is not a completion suggest field]; }{[a64iSYrdS8C4ZA1ah0Hb6A][mudrod][2]: RemoteTransportException[[mudrod-server][192.168.173.35:9300][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[Field [Dataset-Metadata] is not a completion suggest field]; }{[a64iSYrdS8C4ZA1ah0Hb6A][mudrod][3]: RemoteTransportException[[mudrod-server][192.168.173.35:9300][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[Field [Dataset-Metadata] is not a completion suggest field]; }{[a64iSYrdS8C4ZA1ah0Hb6A][mudrod][4]: RemoteTransportException[[mudrod-server][192.168.173.35:9300][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[Field [Dataset-Metadata] is not a completion suggest field]; }
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:208)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:52)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:143)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1024)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1126)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1104)
	at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:621)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:581)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: RemoteTransportException[[mudrod-server][192.168.173.35:9300][indices:data/read/search[phase/query]]]; nested: IllegalArgumentException[Field [Dataset-Metadata] is not a completion suggest field];
Caused by: java.lang.IllegalArgumentException: Field [Dataset-Metadata] is not a completion suggest field
	at org.elasticsearch.search.suggest.completion.CompletionSuggestionBuilder.build(CompletionSuggestionBuilder.java:368)
	at org.elasticsearch.search.suggest.SuggestBuilder.build(SuggestBuilder.java:178)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:718)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:540)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:516)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:251)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:298)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:295)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:610)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Yongyao** [comment]
@fgreg Are you using the latest master branch? If so, you need to remove everything in ES and re-index all the data before calling the auto-completion function.

Let me know if you still have a problem.

**Comment by fgreg** [comment]
@Yongyao Yes latest master branch. We need a better migration strategy than drop and re-index.

**Comment by fgreg** [comment]
Data has been re-indexed
