### ISSUE TITLE
Fails to start the web service

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#131]
@fgreg I got a problem running the latest service in my local eclipse. Is this due to some recent changes that you made?

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2017-04-11 17:31:11,177 WARN  hadoop.ParquetRecordReader (Log.java:error(193)) - Can not initialize counter due to context is not a instance of TaskInputOutputContext, but is org.apache.hadoop.mapreduce.task.TaskAttemptContextImpl
2017-04-11 17:31:11,639 INFO  ontology.OntologyFactory (OntologyFactory.java:getOntology(67)) - Using ontology extension: Local
2017-04-11 17:31:11,645 INFO  process.LocalOntology (LocalOntology.java:<init>(57)) - Creating new ontology
2017-04-11 17:31:12,158 WARN  impl.RDFDefaultErrorHandler (RDFDefaultErrorHandler.java:warning(47)) - unknown-source: {W136} Relative URIs are not permitted in RDF: specifically <ont-policy.rdf>
2017-04-11 17:31:12,561 ERROR core.StandardServer (DirectJDKLog.java:log(182)) - StandardServer.await: create[localhost:8005]: 
**java.net.BindException: Can't assign requested address (Bind failed)**
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at org.apache.catalina.core.StandardServer.await(StandardServer.java:438)
	at org.apache.catalina.startup.Catalina.await(Catalina.java:717)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:663)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:351)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:485)
2017-04-11 17:31:16,609 WARN  loader.WebappClassLoaderBase (DirectJDKLog.java:log(180)) - The web application [mudrod-service] appears to have started a thread named [dispatcher-event-loop-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
 org.apache.spark.rpc.netty.Dispatcher$MessageLoop.run(Dispatcher.scala:207)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 java.lang.Thread.run(Thread.java:745)

**Comment by fgreg** [comment]
@Yongyao no I don't think so. It looks like it can't connect to your port 8005 for some reason. Are you sure you don't have another instance running already?

**Comment by Yongyao** [comment]
@fgreg I don't think 8005 is needed by any of our components. Do you have any idea on this?

BTW, I assume I don't need to change the "svmSgdModel" in the config.xml file anymore. Correct?

**Comment by fgreg** [comment]
Tomcat uses port 8005 by default for a shutdown port I think. Make sure you don't have tomcat running elsewhere.

Yes, svmSgdModel no longer needs to be changed. It is now being loaded as a resource.

**Comment by Yongyao** [comment]
Turns out it was my local network problem. close it
