### ISSUE TITLE
web service can't be started on windows system

### ISSUE THREAD

**Issue by quintinali** [mudrod/mudrod#135]
Apr 12, 2017 8:22:55 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.36
Apr 12, 2017 8:23:20 AM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2017-04-12 08:23:21,152 INFO  main.MudrodEngine (MudrodEngine.java:locateConfig(130)) - File specified by environment variable MUDROD_CONFIG='' could not be loaded. 
2017-04-12 08:23:21,158 INFO  main.MudrodEngine (MudrodEngine.java:locateConfig(136)) - Loaded config file from file:/D:/Java%20workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/mudrod-service/WEB-INF/lib/mudrod-core-0.0.1-SNAPSHOT.jar!/config.xml
Apr 12, 2017 8:23:21 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class gov.nasa.jpl.mudrod.services.MudrodContextListener
java.lang.UnsupportedOperationException: 'posix:permissions' not supported as initial attribute
	at sun.nio.fs.WindowsSecurityDescriptor.fromAttribute(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.createDirectory(Unknown Source)
	at java.nio.file.Files.createDirectory(Unknown Source)
	at java.nio.file.TempFileHelper.create(Unknown Source)
	at java.nio.file.TempFileHelper.createTempDirectory(Unknown Source)
	at java.nio.file.Files.createTempDirectory(Unknown Source)
	at gov.nasa.jpl.mudrod.main.MudrodEngine.decompressSVMWithSGDModel(MudrodEngine.java:181)
	at gov.nasa.jpl.mudrod.main.MudrodEngine.loadConfig(MudrodEngine.java:163)
	at gov.nasa.jpl.mudrod.services.MudrodContextListener.contextInitialized(MudrodContextListener.java:59)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4842)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Apr 12, 2017 8:23:21 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Apr 12, 2017 8:23:21 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/mudrod-service] startup failed due to previous errors
Apr 12, 2017 8:23:21 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-nio-8080"]
Apr 12, 2017 8:23:21 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-nio-8009"]
Apr 12, 2017 8:23:21 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 26327 ms

reference:
http://stackoverflow.com/questions/14415960/java-lang-unsupportedoperationexception-posixpermissions-not-supported-as-in

**Comment by fgreg** [comment]
@quintinali Sorry about that. Can you try modifying `gov.nasa.jpl.mudrod.main.MudrodEngine#decompressSVMWithSGDModel` and changing line 180 to:

```
    File tempDir = Files.createTempDirectory("mudrod").toFile();
    assert tempDir.setWritable(true);
```

And see if that allows you to start it?

**Comment by quintinali** [comment]
@fgreg Thanks. The problem has been solved, however, I still can't start web service on my computer. 

2017-04-14 10:48:00,782 ERROR executor.Executor (Logging.scala:logError(91)) - Exception in task 0.0 in stage 0.0 (TID 0)
org.apache.hadoop.fs.ChecksumException: Checksum error: file:/C:/Users/tinay/AppData/Local/Temp/mudrod7097015449025731183/javaSVMWithSGDModel/metadata/part-00000 at 0 exp: 300998941 got: 511773804
	at org.apache.hadoop.fs.FSInputChecker.verifySums(FSInputChecker.java:322)
	at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:278)
	at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:227)
	at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:195)
	at java.io.DataInputStream.read(Unknown Source)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:211)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:174)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:206)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:45)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:266)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:211)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1353)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1353)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2017-04-14 10:48:00,848 WARN  scheduler.TaskSetManager (Logging.scala:logWarning(66)) - Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): org.apache.hadoop.fs.ChecksumException: Checksum error: file:/C:/Users/tinay/AppData/Local/Temp/mudrod7097015449025731183/javaSVMWithSGDModel/metadata/part-00000 at 0 exp: 300998941 got: 511773804
	at org.apache.hadoop.fs.FSInputChecker.verifySums(FSInputChecker.java:322)
	at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:278)
	at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:227)
	at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:195)
	at java.io.DataInputStream.read(Unknown Source)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:211)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:174)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:206)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:45)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:266)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:211)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1353)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1353)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

2017-04-14 10:48:00,857 ERROR scheduler.TaskSetManager (Logging.scala:logError(70)) - Task 0 in stage 0.0 failed 1 times; aborting job
2017-04-14 10:48:00,928 ERROR [localhost].[/mudrod-service] (DirectJDKLog.java:log(182)) - Exception sending context initialized event to listener instance of class gov.nasa.jpl.mudrod.services.MudrodContextListener
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost, executor driver): org.apache.hadoop.fs.ChecksumException: Checksum error: file:/C:/Users/tinay/AppData/Local/Temp/mudrod7097015449025731183/javaSVMWithSGDModel/metadata/part-00000 at 0 exp: 300998941 got: 511773804
	at org.apache.hadoop.fs.FSInputChecker.verifySums(FSInputChecker.java:322)
	at org.apache.hadoop.fs.FSInputChecker.readChecksumChunk(FSInputChecker.java:278)
	at org.apache.hadoop.fs.FSInputChecker.read1(FSInputChecker.java:227)
	at org.apache.hadoop.fs.FSInputChecker.read(FSInputChecker.java:195)
	at java.io.DataInputStream.read(Unknown Source)
	at org.apache.hadoop.util.LineReader.readDefaultLine(LineReader.java:211)
	at org.apache.hadoop.util.LineReader.readLine(LineReader.java:174)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:206)
	at org.apache.hadoop.mapred.LineRecordReader.next(LineRecordReader.java:45)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:266)
	at org.apache.spark.rdd.HadoopRDD$$anon$1.getNext(HadoopRDD.scala:211)
	at org.apache.spark.util.NextIterator.hasNext(NextIterator.scala:73)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1353)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1353)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1944)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1931)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1944)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1353)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1326)
	at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1367)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.first(RDD.scala:1366)
	at org.apache.spark.mllib.util.Loader$.loadMetadata(modelSaveLoad.scala:129)
	at org.apache.spark.mllib.classification.SVMModel$.load(SVM.scala:100)
	at org.apache.spark.mllib.classification.SVMModel.load(SVM.scala)
	at gov.nasa.jpl.mudrod.ssearch.ranking.Learner.<init>(Learner.java:46)
	at gov.nasa.jpl.mudrod.ssearch.Ranker.<init>(Ranker.java:45)
	at gov.nasa.jpl.mudrod.services.MudrodContextListener.contextInitialized(MudrodContextListener.java:65)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4842)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.hadoop.fs.ChecksumException: Checksum error: file:/C:/Users/tinay/AppData/Local/Temp/mudrod7097015449025731183/javaSVMWithSGDModel/metadata/part-00000 at 0 exp: 300998941 got: 511773804

**Comment by lewismc** [comment]
@quintinali this has to do with the absolute locations set in configuration... make sure that not absolute paths exist. They should all be relative or determined from the classpath.

**Comment by lewismc** [comment]
Also @quintinali can we please always tag issues with the general tags.

**Comment by fgreg** [comment]
@quintinali Can you try checking out this branch https://github.com/mudrod/mudrod/tree/mudrod-135 and then starting the app? Sorry, I don't have a windows machine I can easily test this on.

**Comment by quintinali** [comment]
Thanks for your help. I will try it later and let you know whether it works.

**Comment by Yongyao** [comment]
@quintinali Is this solved? If so, please close it.

**Comment by quintinali** [comment]
@fgreg I encountered the following problem since zip file can't be imported using GzipCompressorInputStream.

2017-05-01 12:27:24,335 ERROR main.MudrodEngine (MudrodEngine.java:loadConfig(169)) - Exception whilst retrieving or processing XML contained within 'config.xml'!
java.io.IOException: Input is not in the .gz format
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.init(GzipCompressorInputStream.java:146)
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:129)
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.<init>(GzipCompressorInputStream.java:94)
	at gov.nasa.jpl.mudrod.main.MudrodEngine.decompressSVMWithSGDModel(MudrodEngine.java:190)
	at gov.nasa.jpl.mudrod.main.MudrodEngine.loadConfig(MudrodEngine.java:163)
	at gov.nasa.jpl.mudrod.services.MudrodContextListener.contextInitialized(MudrodContextListener.java:59)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4842)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

so I changed the decompress archive code using ZipInputStream listed below
`   int BUFFER_SIZE = 512000;
		ZipInputStream zipIn = new ZipInputStream(new FileInputStream(archiveFile));
		ZipEntry entry;
		while ((entry = zipIn.getNextEntry()) != null) {
			// If the entry is a directory, create the directory.
			if (entry.isDirectory()) {
				File f = new File(tempDir, entry.getName());
				boolean created = f.mkdirs();
				if (!created) {
					LOG.error("Unable to create directory '%s', during extraction of archive contents.",
							f.getAbsolutePath());
				}
			} 
		}
		
		zipIn = new ZipInputStream(new FileInputStream(archiveFile));
		while ((entry = zipIn.getNextEntry()) != null) {
			// If the entry is a directory, create the directory.
			if (!entry.isDirectory()) {
				System.out.println("3");
				System.out.println(tempDir+ "/"+ entry.getName());
				int count;
				byte data[] = new byte[BUFFER_SIZE];
				FileOutputStream fos = new FileOutputStream(new File(tempDir, entry.getName()), false);
				try (BufferedOutputStream dest = new BufferedOutputStream(fos, BUFFER_SIZE)) {
					while ((count = zipIn.read(data, 0, BUFFER_SIZE)) != -1) {
						dest.write(data, 0, count);
					}
				}
			}
		}`

The zip model can be copied to the temp directory but can't be loaded successfully because of the issue described in this page
http://stackoverflow.com/questions/15434709/checksum-exception-when-reading-from-or-copying-to-hdfs-in-apache-hadoop

To solve the problem, following files in the core\src\main\resources\javaSVMWithSGDModel folder shoule be deleted 
.part-r-00000-e008ae03-6b61-4931-ba29-27304de5a584.gz.parquet.crc
.part-00000.crc

**Comment by fgreg** [comment]
@quintinali Ah yea I forgot to change the decompression to use zip instead of gzip. Can you check your code in to the branch https://github.com/mudrod/mudrod/tree/mudrod-135 and I'll test on mac/linux to make sure it still works.

**Comment by quintinali** [comment]
@fgreg I submitted my code to branch mudrod-135, please take a look.

**Comment by quintinali** [comment]
@fgreg Could you please submit a pull request if my modification works on your computer? Thanks
