### ISSUE TITLE
NumberFormatException during searches

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#164]
After completing the full log ingest, I now get an error whenever I try to run a search

The request I am issuing is `http://localhost:8080/mudrod-service/services/metadata/search?query=sst&operator=And`

```
2017-05-09 11:15:46,967 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(224)) - 
************************ UserHistoryLinkage results***************************
2017-05-09 11:15:46,971 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(224)) - 
************************ ClickStreamLinkage results***************************
2017-05-09 11:15:46,971 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( iasi 0.97 )
2017-05-09 11:15:46,972 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( modi jpl l2p v2014.0 0.93 )
2017-05-09 11:15:46,972 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( chlorophyll 0.85 )
2017-05-09 11:15:46,972 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( viir 0.47 )
2017-05-09 11:15:46,972 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( oxygen 0.38 )
2017-05-09 11:15:46,972 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( suomi npp 0.38 )
2017-05-09 11:15:46,972 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( ocean chemistry 0.38 )
2017-05-09 11:15:46,972 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( viir sst 0.38 )
2017-05-09 11:15:46,972 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( atlantic ocean 0.29 )
2017-05-09 11:15:46,973 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( ghrsst 0.2 )
2017-05-09 11:15:46,973 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( land sea mask 0.19 )
2017-05-09 11:15:46,978 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(224)) - 
************************ MetadataLinkage results***************************
2017-05-09 11:15:46,978 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( sea surface temperature 0.98 )
2017-05-09 11:15:46,978 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( ocean temperature 0.95 )
2017-05-09 11:15:46,978 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( surface temperature 0.83 )
2017-05-09 11:15:46,978 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( ghrsst 0.82 )
2017-05-09 11:15:46,979 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( ocean 0.52 )
2017-05-09 11:15:46,979 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( l2p 0.52 )
2017-05-09 11:15:46,979 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( global 0.5 )
2017-05-09 11:15:46,979 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( pacific ocean 0.48 )
2017-05-09 11:15:46,979 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( polar 0.47 )
2017-05-09 11:15:46,980 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( microwave sst 0.47 )
2017-05-09 11:15:46,980 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTerms(232)) - ( sun synchronous 0.47 )
2017-05-09 11:15:46,983 INFO  integration.LinkageIntegration (LinkageIntegration.java:aggregateRelatedTermsSWEET(248)) - 
************************ SWEETLinkage results***************************
2017-05-09 11:15:47,006 ERROR services.DefaultExceptionMapper (DefaultExceptionMapper.java:toResponse(38)) - Internal server error d16a2730-554c-4d8e-87c5-f7cb60a5f613
Failed to execute phase [query], all shards failed; shardFailures {[nUShbJdnSbu_L3IczOvkXQ][mudrod][0]: RemoteTransportException[[nUShbJd][10.200.10.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[failed to create query: {
  "bool" : {
    "should" : [
      {
        "multi_match" : {
          "query" : "sst",
          "fields" : [
            "Dataset-LongName^1.0",
            "Dataset-Metadata^1.0",
            "Dataset-ShortName^1.0",
            "DatasetParameter-*^1.0",
            "DatasetSource-Sensor-LongName^1.0",
            "DatasetSource-Sensor-LongName-Full^1.0",
            "DatasetSource-Sensor-ShortName^1.0",
            "DatasetSource-Sensor-ShortName-Full^1.0",
            "DatasetSource-Source-LongName^1.0",
            "DatasetSource-Source-LongName-Full^1.0",
            "DatasetSource-Source-ShortName^1.0",
            "DatasetSource-Source-ShortName-Full^1.0"
          ],
          "type" : "best_fields",
          "operator" : "AND",
          "slop" : 0,
          "prefix_length" : 0,
          "max_expansions" : 50,
          "tie_breaker" : 0.5,
          "lenient" : false,
          "zero_terms_query" : "NONE",
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}]; nested: NumberFormatException[For input string: "sst"]; }{[nUShbJdnSbu_L3IczOvkXQ][mudrod][1]: RemoteTransportException[[nUShbJd][10.200.10.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[failed to create query: {
  "bool" : {
    "should" : [
      {
        "multi_match" : {
          "query" : "sst",
          "fields" : [
            "Dataset-LongName^1.0",
            "Dataset-Metadata^1.0",
            "Dataset-ShortName^1.0",
            "DatasetParameter-*^1.0",
            "DatasetSource-Sensor-LongName^1.0",
            "DatasetSource-Sensor-LongName-Full^1.0",
            "DatasetSource-Sensor-ShortName^1.0",
            "DatasetSource-Sensor-ShortName-Full^1.0",
            "DatasetSource-Source-LongName^1.0",
            "DatasetSource-Source-LongName-Full^1.0",
            "DatasetSource-Source-ShortName^1.0",
            "DatasetSource-Source-ShortName-Full^1.0"
          ],
          "type" : "best_fields",
          "operator" : "AND",
          "slop" : 0,
          "prefix_length" : 0,
          "max_expansions" : 50,
          "tie_breaker" : 0.5,
          "lenient" : false,
          "zero_terms_query" : "NONE",
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}]; nested: NumberFormatException[For input string: "sst"]; }{[nUShbJdnSbu_L3IczOvkXQ][mudrod][2]: RemoteTransportException[[nUShbJd][10.200.10.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[failed to create query: {
  "bool" : {
    "should" : [
      {
        "multi_match" : {
          "query" : "sst",
          "fields" : [
            "Dataset-LongName^1.0",
            "Dataset-Metadata^1.0",
            "Dataset-ShortName^1.0",
            "DatasetParameter-*^1.0",
            "DatasetSource-Sensor-LongName^1.0",
            "DatasetSource-Sensor-LongName-Full^1.0",
            "DatasetSource-Sensor-ShortName^1.0",
            "DatasetSource-Sensor-ShortName-Full^1.0",
            "DatasetSource-Source-LongName^1.0",
            "DatasetSource-Source-LongName-Full^1.0",
            "DatasetSource-Source-ShortName^1.0",
            "DatasetSource-Source-ShortName-Full^1.0"
          ],
          "type" : "best_fields",
          "operator" : "AND",
          "slop" : 0,
          "prefix_length" : 0,
          "max_expansions" : 50,
          "tie_breaker" : 0.5,
          "lenient" : false,
          "zero_terms_query" : "NONE",
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}]; nested: NumberFormatException[For input string: "sst"]; }{[nUShbJdnSbu_L3IczOvkXQ][mudrod][3]: RemoteTransportException[[nUShbJd][10.200.10.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[failed to create query: {
  "bool" : {
    "should" : [
      {
        "multi_match" : {
          "query" : "sst",
          "fields" : [
            "Dataset-LongName^1.0",
            "Dataset-Metadata^1.0",
            "Dataset-ShortName^1.0",
            "DatasetParameter-*^1.0",
            "DatasetSource-Sensor-LongName^1.0",
            "DatasetSource-Sensor-LongName-Full^1.0",
            "DatasetSource-Sensor-ShortName^1.0",
            "DatasetSource-Sensor-ShortName-Full^1.0",
            "DatasetSource-Source-LongName^1.0",
            "DatasetSource-Source-LongName-Full^1.0",
            "DatasetSource-Source-ShortName^1.0",
            "DatasetSource-Source-ShortName-Full^1.0"
          ],
          "type" : "best_fields",
          "operator" : "AND",
          "slop" : 0,
          "prefix_length" : 0,
          "max_expansions" : 50,
          "tie_breaker" : 0.5,
          "lenient" : false,
          "zero_terms_query" : "NONE",
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}]; nested: NumberFormatException[For input string: "sst"]; }{[nUShbJdnSbu_L3IczOvkXQ][mudrod][4]: RemoteTransportException[[nUShbJd][10.200.10.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[failed to create query: {
  "bool" : {
    "should" : [
      {
        "multi_match" : {
          "query" : "sst",
          "fields" : [
            "Dataset-LongName^1.0",
            "Dataset-Metadata^1.0",
            "Dataset-ShortName^1.0",
            "DatasetParameter-*^1.0",
            "DatasetSource-Sensor-LongName^1.0",
            "DatasetSource-Sensor-LongName-Full^1.0",
            "DatasetSource-Sensor-ShortName^1.0",
            "DatasetSource-Sensor-ShortName-Full^1.0",
            "DatasetSource-Source-LongName^1.0",
            "DatasetSource-Source-LongName-Full^1.0",
            "DatasetSource-Source-ShortName^1.0",
            "DatasetSource-Source-ShortName-Full^1.0"
          ],
          "type" : "best_fields",
          "operator" : "AND",
          "slop" : 0,
          "prefix_length" : 0,
          "max_expansions" : 50,
          "tie_breaker" : 0.5,
          "lenient" : false,
          "zero_terms_query" : "NONE",
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}]; nested: NumberFormatException[For input string: "sst"]; }
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:208)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:52)
	at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:143)
	at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:51)
	at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1024)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1126)
	at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1104)
	at org.elasticsearch.transport.TransportService$7.onFailure(TransportService.java:621)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.onFailure(ThreadContext.java:581)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: RemoteTransportException[[nUShbJd][10.200.10.1:9300][indices:data/read/search[phase/query]]]; nested: QueryShardException[failed to create query: {
  "bool" : {
    "should" : [
      {
        "multi_match" : {
          "query" : "sst",
          "fields" : [
            "Dataset-LongName^1.0",
            "Dataset-Metadata^1.0",
            "Dataset-ShortName^1.0",
            "DatasetParameter-*^1.0",
            "DatasetSource-Sensor-LongName^1.0",
            "DatasetSource-Sensor-LongName-Full^1.0",
            "DatasetSource-Sensor-ShortName^1.0",
            "DatasetSource-Sensor-ShortName-Full^1.0",
            "DatasetSource-Source-LongName^1.0",
            "DatasetSource-Source-LongName-Full^1.0",
            "DatasetSource-Source-ShortName^1.0",
            "DatasetSource-Source-ShortName-Full^1.0"
          ],
          "type" : "best_fields",
          "operator" : "AND",
          "slop" : 0,
          "prefix_length" : 0,
          "max_expansions" : 50,
          "tie_breaker" : 0.5,
          "lenient" : false,
          "zero_terms_query" : "NONE",
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}]; nested: NumberFormatException[For input string: "sst"];
Caused by: [mudrod/jblgPvDPSg-uQDEU2HOWzw] QueryShardException[failed to create query: {
  "bool" : {
    "should" : [
      {
        "multi_match" : {
          "query" : "sst",
          "fields" : [
            "Dataset-LongName^1.0",
            "Dataset-Metadata^1.0",
            "Dataset-ShortName^1.0",
            "DatasetParameter-*^1.0",
            "DatasetSource-Sensor-LongName^1.0",
            "DatasetSource-Sensor-LongName-Full^1.0",
            "DatasetSource-Sensor-ShortName^1.0",
            "DatasetSource-Sensor-ShortName-Full^1.0",
            "DatasetSource-Source-LongName^1.0",
            "DatasetSource-Source-LongName-Full^1.0",
            "DatasetSource-Source-ShortName^1.0",
            "DatasetSource-Source-ShortName-Full^1.0"
          ],
          "type" : "best_fields",
          "operator" : "AND",
          "slop" : 0,
          "prefix_length" : 0,
          "max_expansions" : 50,
          "tie_breaker" : 0.5,
          "lenient" : false,
          "zero_terms_query" : "NONE",
          "boost" : 1.0
        }
      }
    ],
    "disable_coord" : false,
    "adjust_pure_negative" : true,
    "boost" : 1.0
  }
}]; nested: NumberFormatException[For input string: "sst"];
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:333)
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:311)
	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:671)
	at org.elasticsearch.search.SearchService.createContext(SearchService.java:540)
	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:516)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:251)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:298)
	at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:295)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:610)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:596)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "sst"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$2.parse(NumberFieldMapper.java:273)
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberType$2.termQuery(NumberFieldMapper.java:283)
	at org.elasticsearch.index.mapper.NumberFieldMapper$NumberFieldType.termQuery(NumberFieldMapper.java:904)
	at org.elasticsearch.index.search.MatchQuery.termQuery(MatchQuery.java:279)
	at org.elasticsearch.index.search.MatchQuery.blendTermQuery(MatchQuery.java:402)
	at org.elasticsearch.index.search.MultiMatchQuery.access$201(MultiMatchQuery.java:50)
	at org.elasticsearch.index.search.MultiMatchQuery$QueryBuilder.blendTerm(MultiMatchQuery.java:158)
	at org.elasticsearch.index.search.MultiMatchQuery.blendTermQuery(MultiMatchQuery.java:340)
	at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:243)
	at org.elasticsearch.index.search.MultiMatchQuery.parseAndApply(MultiMatchQuery.java:63)
	at org.elasticsearch.index.search.MultiMatchQuery.access$100(MultiMatchQuery.java:50)
	at org.elasticsearch.index.search.MultiMatchQuery$QueryBuilder.parseGroup(MultiMatchQuery.java:132)
	at org.elasticsearch.index.search.MultiMatchQuery$QueryBuilder.buildGroupedQueries(MultiMatchQuery.java:123)
	at org.elasticsearch.index.search.MultiMatchQuery.parse(MultiMatchQuery.java:97)
	at org.elasticsearch.index.query.MultiMatchQueryBuilder.doToQuery(MultiMatchQueryBuilder.java:747)
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97)
	at org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(BoolQueryBuilder.java:442)
	at org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(BoolQueryBuilder.java:418)
	at org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(AbstractQueryBuilder.java:97)
	at org.elasticsearch.index.query.QueryShardContext.lambda$toQuery$1(QueryShardContext.java:312)
	at org.elasticsearch.index.query.QueryShardContext.toQuery(QueryShardContext.java:329)
	... 14 more
```

**Comment by Yongyao** [comment]
@fgreg This is due to the recent upgrade of ES API I think. It was fixed in this PR https://github.com/mudrod/mudrod/pull/154/files#diff-f0f82dbbaa887ab6a2696f34ea930730L94

I think https://github.com/mudrod/mudrod/pull/154 has no problem (only 2 minor changes were made), but it is experiencing a build failure. Can you help take a look? After it is merged, this error would disappear.

**Comment by fgreg** [comment]
@Yongyao I don't see how the changes in that commit would affect searching. The only Java file that changed seems unrelated to searching.

**Comment by Yongyao** [comment]
@fgreg The fields in the `fieldsList` are the ones that all the queries are based on. This problem is that ES somehow does not understand the wildcard `DatasetParameter-*` any more. I therefore defined it explicitly in the PR.

**Comment by fgreg** [comment]
This is resolved by https://github.com/mudrod/mudrod/pull/154
