### ISSUE TITLE
Full ingest - Error ingesting SSL logs

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#167]
When running full log ingestion on the 03-2017 logs, an error is thrown during processing:

```
2017-05-09 21:21:02,249 INFO  discoveryengine.WeblogDiscoveryEngine (WeblogDiscoveryEngine.java:preprocess(125)) - Web log preprocessing for logs dated 201703.gz complete. Time elapsed 2740 seconds.
2017-05-09 21:21:02,249 INFO  discoveryengine.WeblogDiscoveryEngine (WeblogDiscoveryEngine.java:preprocess(106)) - Processing logs dated ssl_201703.gz
2017-05-09 21:21:02,421 INFO  pre.ImportLogFile (ImportLogFile.java:execute(74)) - Starting Log Import ssl_201703.gz
usage: MudrodEngine: 'dataDir' argument is mandatory. User must also
       provide an ingest method. -dataDir </path/to/data/directory>
       [-esHost <host_name>] [-esPort <port_num>] [-esTCPPort <port_num>]
       [-f] [-h] [-l] [-m] [-p]
 -dataDir,--dataDirectory </path/to/data/directory>      the data
                                                         directory to be
                                                         processed by
                                                         Mudrod
 -esHost,--elasticSearchHost <host_name>                 elasticsearch
                                                         cluster unicast
                                                         host
 -esPort,--elasticSearchHTTPPort <port_num>              elasticsearch
                                                         HTTP/REST port
 -esTCPPort,--elasticSearchTransportTCPPort <port_num>   elasticsearch
                                                         transport TCP
                                                         port
 -f,--fullIngest                                         begin full ingest
                                                         Mudrod workflow
 -h,--help                                               show this help
                                                         message
 -l,--logIngest                                          begin log ingest
 -m,--metaIngest                                         begin metadata
                                                         ingest
 -p,--processingWithPreResults                           begin processing
                                                         with
                                                         preprocessing
                                                         results
2017-05-09 21:21:02,500 ERROR main.MudrodEngine (MudrodEngine.java:main(398)) - Error whilst parsing command line.
org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/usr/local/sdeploy/mudrod-ingest/ftp-mirror/2017/03/WWW.ssl_201703.gz
	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:251)
	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:270)
	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:202)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.elasticsearch.spark.rdd.EsSpark$.doSaveToEs(EsSpark.scala:91)
	at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:76)
	at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:73)
	at org.elasticsearch.spark.rdd.EsSpark$.saveJsonToEs(EsSpark.scala:106)
	at org.elasticsearch.spark.rdd.api.java.JavaEsSpark$.saveJsonToEs(JavaEsSpark.scala:62)
	at org.elasticsearch.spark.rdd.api.java.JavaEsSpark.saveJsonToEs(JavaEsSpark.scala)
	at gov.nasa.jpl.mudrod.weblog.pre.ImportLogFile.importHttpfile(ImportLogFile.java:170)
	at gov.nasa.jpl.mudrod.weblog.pre.ImportLogFile.readFileInParallel(ImportLogFile.java:162)
	at gov.nasa.jpl.mudrod.weblog.pre.ImportLogFile.readFile(ImportLogFile.java:130)
	at gov.nasa.jpl.mudrod.weblog.pre.ImportLogFile.execute(ImportLogFile.java:76)
	at gov.nasa.jpl.mudrod.discoveryengine.WeblogDiscoveryEngine.preprocess(WeblogDiscoveryEngine.java:109)
	at gov.nasa.jpl.mudrod.main.MudrodEngine.startFullIngest(MudrodEngine.java:241)
	at gov.nasa.jpl.mudrod.main.MudrodEngine.main(MudrodEngine.java:388)
```

**Comment by fgreg** [comment]
Note the March logs contain the following files:

```
    ├── 03
    │   ├── FTP.201703.gz
    │   ├── LAS.201703.gz
    │   ├── OPeNDAP.201703.gz
    │   ├── ssl_OPeNDAP.201703.gz
    │   ├── ssl_THREDDS.201703.gz
    │   ├── ssl_WWW.201703.gz
    │   ├── THREDDS.201703.gz
    │   └── WWW.201703.gz
```

And the April logs contain only the ssl files:

```
    └── 04
        ├── ssl_FTP.201704.gz
        ├── ssl_OPeNDAP.201704.gz
        ├── ssl_THREDDS.201704.gz
        └── ssl_WWW.201704.gz
```

We should be able to handle both.

**Comment by quintinali** [comment]
@fgreg  Could you please tell me where did you download logs of 201703? From my side,  I can only see ssl and las logs in ftp://podaac.jpl.nasa.gov/misc/outgoing/cjf/mudrod/2017/03/

├── 03
    │   ├── LAS.201703.gz
    │   ├── ssl_OPeNDAP.201703.gz
    │   ├── ssl_THREDDS.201703.gz
    │   ├── ssl_WWW.201703.gz

**Comment by fgreg** [comment]
@quintinali Ah it's possible that the non-ssl logs were there previously, I downloaded them, then they were changed to the ssl_ ones and I downloaded them again.

**Comment by Yongyao** [comment]
@fgreg I wonder, what "ssl" is? and what is the difference between "ssl_WWW.201703.gz" and "WWW.201703.gz"?

**Comment by fgreg** [comment]
@Yongyao I think this is related to the effort early this year to ensure all JPL websites are served over https. I think WWW.201703.gz became ssl_WWW.201703.gz when it changed from http to https.

This may also be the reason the log ingestion isn't working; are we matching on http only, not https?

**Comment by Yongyao** [comment]
It should have been solved through this PR https://github.com/mudrod/mudrod/pull/170
