### ISSUE TITLE
DateFormat Parse Exception

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#176]
Error when trying to ingest the 2016/12 logs.

Command used was `mudrod-engine -f -dataDir /Users/greguska/data/mudrod/201612`

```
2017-05-23 13:02:28,601 INFO  discoveryengine.WeblogDiscoveryEngine (WeblogDiscoveryEngine.java:<init>(51)) - Started Mudrod Weblog Discovery Engine.
2017-05-23 13:02:28,601 INFO  discoveryengine.WeblogDiscoveryEngine (WeblogDiscoveryEngine.java:preprocess(98)) - Starting Web log preprocessing.
2017-05-23 13:02:28,601 INFO  discoveryengine.WeblogDiscoveryEngine (WeblogDiscoveryEngine.java:preprocess(106)) - Processing logs dated 201612.w1
2017-05-23 13:02:28,828 INFO  pre.ImportLogFile (ImportLogFile.java:execute(75)) - Starting Log Import 201612.w1
2017-05-23 13:02:29,677 INFO  util.Version (Version.java:logVersion(108)) - Elasticsearch Hadoop v5.2.0 [d85a257f9f]
2017-05-23 13:02:30,091 INFO  rdd.EsRDDWriter (RestService.java:createWriter(562)) - Writing to [podaaclog201612.w1/rawhttp]
2017-05-23 13:04:16,792 INFO  rdd.EsRDDWriter (RestService.java:createWriter(562)) - Writing to [podaaclog201612.w1/rawftp]
2017-05-23 13:04:48,752 ERROR executor.Executor (Logging.scala:logError(91)) - Exception in task 0.0 in stage 1.0 (TID 1)
java.text.ParseException: Unparseable date: "12:3Fri:12:30"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at gov.nasa.jpl.mudrod.weblog.structure.FtpLog.parseFromLogLine(FtpLog.java:38)
        at gov.nasa.jpl.mudrod.weblog.pre.ImportLogFile.lambda$importFtpfile$7bd28f6a$1(ImportLogFile.java:198)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1040)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:66)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:102)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:102)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-05-23 13:04:48,789 WARN  scheduler.TaskSetManager (Logging.scala:logWarning(66)) - Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.text.ParseException: Unparseable date: "12:3Fri:12:30"
        at java.text.DateFormat.parse(DateFormat.java:366)
        at gov.nasa.jpl.mudrod.weblog.structure.FtpLog.parseFromLogLine(FtpLog.java:38)
        at gov.nasa.jpl.mudrod.weblog.pre.ImportLogFile.lambda$importFtpfile$7bd28f6a$1(ImportLogFile.java:198)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1040)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:66)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:102)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:102)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by fgreg** [comment]
@quintinali Can you look at this issue as well? It's still happening with latest from master. Only for the 2016/12 logs so far though.

**Comment by quintinali** [comment]
@fgreg Ok, I will try to solve this issue sooner

**Comment by quintinali** [comment]
@fgreg  The last line of FTP.201612.w1.gz is:

Fri Dec 3Fri Dec 30 11:00:00 2016 1 46.4.24.6 78 /allData/aquarius/L3/mapped/V4/7day_running/SCI/2013/147/Q20131472013153.L3m_R7_SCI_V4.0_SSS_1deg.bz2.md5 b _ o a lftp@ ftp 0 * c

A normal one is: 
Wed Dec  7 23:59:59 2016 2 146.201.68.146 20485891 /allData/quikscat/L2B12/v3.1/2000/298/qs_l2b_07018_v3.1_200010240131.nc.gz b _ o a campbell@ ftp 0 * c

Comparing above two logs, It is obvious that the date in the first log is wrong. That's why date format can't be parsed. I will add some codes to handle this kind of exception.

**Comment by quintinali** [comment]
@fgreg please check PR https://github.com/mudrod/mudrod/pull/180

**Comment by fgreg** [comment]
Fixed by PR https://github.com/mudrod/mudrod/pull/180
