### ISSUE TITLE
RawMetadata Deleted

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#177]
I was trying to ingest 2017/01 data and it seemed to ingest all the way through week 5. But then an exception was thrown and now the 'mudrod' index no longer contains any 'RawMetadata' documents.

The full log is available and the error starts at line 1045:

https://gist.github.com/fgreg/d8592cbd5d04983c5b78d63256016494#file-mudrod-ingest-201701-log-L1045

Why did this wipe out all `RawMetadata` documents from my `mudrod` index? Now it seems like I have to re-ingest everything again.

**Comment by quintinali** [comment]
@fgreg Did you use the master branch? I can't reproduce the bug in my laptop.

**Comment by fgreg** [comment]
Yes this was using master branch. 2016/11 logs were already ingested and when I tried 2017/01 this error occurred and then all data was missing.

I've wiped the index and am trying a fresh ingest of just 2017/01 now. I'll see if it happens again.

**Comment by fgreg** [comment]
@quintinali Even starting with an empty index I get this error:

```
2017-05-24 18:58:33,854 ERROR process.ClickStreamAnalyzer (ClickStreamAnalyzer.java:execute(66)) - Encountered an error during execution of ClickStreamAnalyzer.
java.lang.IllegalArgumentException: Field name cannot be null
        at org.elasticsearch.common.xcontent.XContentBuilder.ensureNotNull(XContentBuilder.java:1028)
        at org.elasticsearch.common.xcontent.XContentBuilder.ensureNameNotNull(XContentBuilder.java:1019)
        at org.elasticsearch.common.xcontent.XContentBuilder.field(XContentBuilder.java:245)
        at org.elasticsearch.common.xcontent.XContentBuilder.startObject(XContentBuilder.java:222)
        at gov.nasa.jpl.mudrod.ssearch.ClickstreamImporter.addClickStreamMapping(ClickstreamImporter.java:53)
        at gov.nasa.jpl.mudrod.ssearch.ClickstreamImporter.<init>(ClickstreamImporter.java:44)
        at gov.nasa.jpl.mudrod.weblog.process.ClickStreamAnalyzer.execute(ClickStreamAnalyzer.java:62)
        at gov.nasa.jpl.mudrod.discoveryengine.WeblogDiscoveryEngine.process(WeblogDiscoveryEngine.java:186)
        at gov.nasa.jpl.mudrod.main.MudrodEngine.startFullIngest(MudrodEngine.java:257)
        at gov.nasa.jpl.mudrod.main.MudrodEngine.main(MudrodEngine.java:401)
```

Followed by 
```
2017-05-24 18:58:54,845 INFO  process.MetadataAnalyzer (MetadataAnalyzer.java:execute(66)) - *****************Metadata Analyzer starts******************
org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/usr/local/sdeploy/mudrod-ingest/ftp-mirror/2017/02/MetadataMatrix.csv
        at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:251)
        at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:270)
        at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:202)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
        at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
        at org.apache.spark.rdd.ZippedWithIndexRDD.<init>(ZippedWithIndexRDD.scala:44)
        at org.apache.spark.rdd.RDD$$anonfun$zipWithIndex$1.apply(RDD.scala:1293)
        at org.apache.spark.rdd.RDD$$anonfun$zipWithIndex$1.apply(RDD.scala:1293)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
        at org.apache.spark.rdd.RDD.zipWithIndex(RDD.scala:1292)
        at org.apache.spark.api.java.JavaRDDLike$class.zipWithIndex(JavaRDDLike.scala:342)
        at org.apache.spark.api.java.AbstractJavaRDDLike.zipWithIndex(JavaRDDLike.scala:45)
        at gov.nasa.jpl.mudrod.utils.MatrixUtil.loadVectorFromCSV(MatrixUtil.java:359)
        at gov.nasa.jpl.mudrod.semantics.SVDAnalyzer.getSVDMatrix(SVDAnalyzer.java:59)
        at gov.nasa.jpl.mudrod.metadata.process.MetadataAnalyzer.execute(MetadataAnalyzer.java:74)
        at gov.nasa.jpl.mudrod.discoveryengine.MetadataDiscoveryEngine.process(MetadataDiscoveryEngine.java:67)
        at gov.nasa.jpl.mudrod.main.MudrodEngine.startFullIngest(MudrodEngine.java:261)
        at gov.nasa.jpl.mudrod.main.MudrodEngine.main(MudrodEngine.java:401)
2017-05-24 18:58:54,859 INFO  process.MetadataAnalyzer (MetadataAnalyzer.java:execute(85)) - *****************Metadata Analyzer ends******************Took 0s
```

And no `RawMetadata` in the index.

**Comment by quintinali** [comment]
@fgreg I will try to reingest logs from my side

**Comment by quintinali** [comment]
@freg please check the PR 179 https://github.com/mudrod/mudrod/pull/179.
