### ISSUE TITLE
NumberFormatException: For input string: "Dec"

### ISSUE THREAD

**Issue by fgreg** [mudrod/mudrod#181]
While trying to ingest 2016/12 logs:

```
2017-05-25 21:56:25,626 INFO  pre.ImportLogFile (ImportLogFile.java:execute(75)) - Starting Log Import 201612.w5.gz
2017-05-25 21:56:25,659 INFO  rdd.EsRDDWriter (RestService.java:createWriter(562)) - Writing to [podaaclog201612.w5.gz/rawhttp]
2017-05-25 21:56:48,165 INFO  rdd.EsRDDWriter (RestService.java:createWriter(562)) - Writing to [podaaclog201612.w5.gz/rawftp]
2017-05-25 21:57:15,117 ERROR executor.Executor (Logging.scala:logError(91)) - Exception in task 0.0 in stage 45.0 (TID 1977)
java.lang.NumberFormatException: For input string: "Dec"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at gov.nasa.jpl.mudrod.weblog.structure.FtpLog.parseFromLogLine(FtpLog.java:61)
        at gov.nasa.jpl.mudrod.weblog.pre.ImportLogFile.lambda$importFtpfile$7bd28f6a$1(ImportLogFile.java:198)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1040)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:66)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:102)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:102)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by lzz156** [comment]
tongyang d wenti
