### ISSUE TITLE
java.lang.RuntimeException: Cannot determine the number of rows because it is not specified in the constructor and the rows RDD is empty.

### ISSUE THREAD

**Issue by lewismc** [mudrod/mudrod#57]
This is when running a logIngest from the temp0907 branch with some local modifications I've been working on.

```
lmcgibbn@LMC-032857 /usr/local/mudrod(temp0907) $ ./core/target/appassembler/bin/mudrod -f -logDir /usr/local/mudrod_resources/logDir
java.lang.RuntimeException: Cannot determine the number of rows because it is not specified in the constructor and the rows RDD is empty.
        at scala.sys.package$.error(package.scala:27)
        at org.apache.spark.mllib.linalg.distributed.RowMatrix.numRows(RowMatrix.scala:77)
        at esiptestbed.mudrod.utils.MatrixUtil.exportToCSV(MatrixUtil.java:504)
        at esiptestbed.mudrod.weblog.pre.ClickStreamGenerator.execute(ClickStreamGenerator.java:64)
        at esiptestbed.mudrod.discoveryengine.WeblogDiscoveryEngine.preprocess(WeblogDiscoveryEngine.java:125)
        at esiptestbed.mudrod.main.MudrodEngine.startFullIngest(MudrodEngine.java:158)
        at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:357)
```

**Comment by lewismc** [comment]
Also included within the log is the following exception

```
java.lang.UnsupportedOperationException: empty collection
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$apply$35.apply(RDD.scala:985)
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$apply$35.apply(RDD.scala:985)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:985)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
        at org.apache.spark.rdd.RDD.reduce(RDD.scala:965)
        at org.apache.spark.mllib.linalg.distributed.IndexedRowMatrix.numRows(IndexedRowMatrix.scala:66)
        at org.apache.spark.mllib.linalg.distributed.IndexedRowMatrix.toCoordinateMatrix(IndexedRowMatrix.scala:128)
        at esiptestbed.mudrod.utils.MatrixUtil.transposeMatrix(MatrixUtil.java:487)
        at esiptestbed.mudrod.utils.SimilarityUtil.CalSimilarityFromVector(SimilarityUtil.java:62)
        at esiptestbed.mudrod.semantics.SemanticAnalyzer.calTermSimfromMatrix(SemanticAnalyzer.java:69)
        at esiptestbed.mudrod.semantics.SemanticAnalyzer.calTermSimfromMatrix(SemanticAnalyzer.java:60)
        at esiptestbed.mudrod.weblog.process.UserHistoryAnalyzer.execute(UserHistoryAnalyzer.java:54)
        at esiptestbed.mudrod.discoveryengine.WeblogDiscoveryEngine.process(WeblogDiscoveryEngine.java:202)
        at esiptestbed.mudrod.main.MudrodEngine.startFullIngest(MudrodEngine.java:159)
        at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:357)
```

**Comment by Yongyao** [comment]
The logDir data you are using are not designed for this. Yun will share some logs with you

**Comment by lewismc** [comment]
... please as soon as possible. I have upgraded to Spark 2.0.0 and would like to address this before the weekend comes up. Thanks.

**Comment by lewismc** [comment]
We need to have the logDir available from google drive and the link shared to mudrod-all@ list please. This is a waste of time if we don't have the most up-to-date code and resources available. Thanks I appreciate it.

**Comment by quintinali** [comment]
Here is the link for test logs.
https://drive.google.com/open?id=0BwHfRxX3bkBTcGVhRENpMEdnVnc
I also sent them to your Gmail.

**Comment by lewismc** [comment]
Thank you very much @quintinali this is great.

**Comment by lewismc** [comment]
This is fixed by using the correct inputs however we need to improve Exception handling at some point to accommodate the possibility of files not being present.
