### ISSUE TITLE
Testing data issues

### ISSUE THREAD

**Issue by Yongyao** [mudrod/mudrod#85]
@lewismc @fgreg 

There was something wrong with the data you were using. Just downloaded the data that we put in the docker before, it works fine now. You can access it here https://drive.google.com/open?id=0B5cX6Zn-YwkxZUNjSkRIZDROVFk

A few notes here,
1) "Testing_Data_1_3dayLog+Meta+Onto" is **only** made for testing log ingesting function, so please only use it with "-l" command. When it is finished (5-10mins), you would see the following message. If you run it with other commands like ‘‘-p, -f", there might be an error.

![image](https://cloud.githubusercontent.com/assets/5552606/22528233/61620e1c-e8a0-11e6-9439-e35a3da44895.png)

2) "Testing_Data_2_ProcessedLog+Meta+Onto" is **only** made for testing the data mining functions including web services, please run it with '-p'. After it finishes (5-10mins), you can start the web service to see the UI and interact with the results.

![image](https://cloud.githubusercontent.com/assets/5552606/22528446/49134a00-e8a1-11e6-9568-2ca88f9a0d5e.png)

3) Each time you switch from data 1 to 2, please delete everything in Elasticsearch.

**Comment by lewismc** [comment]
Thank you @Yongyao

**Comment by lewismc** [comment]
The new datasets are working excellently. Thank you @Yongyao

**Comment by lewismc** [comment]
OK, it turns out that this is not quite as expected using current master branch. I am investigating.

**Comment by lewismc** [comment]
This issue is resolved.

**Comment by fgreg** [comment]
@Yongyao I am having problems with Testing_Data_2_ProcessedLog+Meta+Onto. My index is empty and I am running it with the command `/core/target/appassembler/bin/mudrod-engine -p -logDir /Users/greguska/Downloads/mudrod_test_data/Testing_Data_2_ProcessedLog+Meta+Onto/`

It start running but fails with the following stacktrace:

    2017-02-06 12:07:13,250 INFO  process.AbstractBasedSimilarity (AbstractBasedSimilarity.java:execute(50)) - *****************abstract similarity calculation starts******************
    org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/Users/greguska/Downloads/mudrod_test_data/Testing_Data_2_ProcessedLog+Meta+Onto/metadata_word_tfidf.csv
            at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:251)
            at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:270)
            at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:202)
            at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
            at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
            at scala.Option.getOrElse(Option.scala:121)
            at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
            at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
            at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
            at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
            at scala.Option.getOrElse(Option.scala:121)
            at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
            at org.apache.spark.rdd.ZippedWithIndexRDD.<init>(ZippedWithIndexRDD.scala:44)
            at org.apache.spark.rdd.RDD$$anonfun$zipWithIndex$1.apply(RDD.scala:1293)
            at org.apache.spark.rdd.RDD$$anonfun$zipWithIndex$1.apply(RDD.scala:1293)
            at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
            at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
            at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
            at org.apache.spark.rdd.RDD.zipWithIndex(RDD.scala:1292)
            at org.apache.spark.api.java.JavaRDDLike$class.zipWithIndex(JavaRDDLike.scala:342)
            at org.apache.spark.api.java.AbstractJavaRDDLike.zipWithIndex(JavaRDDLike.scala:45)
            at esiptestbed.mudrod.utils.MatrixUtil.loadVectorFromCSV(MatrixUtil.java:423)
            at esiptestbed.mudrod.semantics.SVDAnalyzer.getSVDMatrix(SVDAnalyzer.java:63)
            at esiptestbed.mudrod.recommendation.process.AbstractBasedSimilarity.execute(AbstractBasedSimilarity.java:64)
            at esiptestbed.mudrod.discoveryengine.RecommendEngine.process(RecommendEngine.java:71)
            at esiptestbed.mudrod.main.MudrodEngine.startProcessing(MudrodEngine.java:270)
            at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:411)


Can you provide some guidance?

**Comment by quintinali** [comment]
@fgreg one csv file was missing in the Testing_Data_2_ProcessedLog+Meta+Onto directory. I will upload it, please redownload the directory and try it again.

**Comment by quintinali** [comment]
@fgreg please use files in the attached directory. 
[Testing_Data_2_ProcessedLog+Meta+Onto.zip](https://github.com/mudrod/mudrod/files/761925/Testing_Data_2_ProcessedLog.Meta.Onto.zip)

**Comment by lewismc** [comment]
@fgreg PING can you try again please and confirm? If you are satisfied then please close this issue off. Thanks.

**Comment by fgreg** [comment]
I'll test out the update today or tomorrow and confirm.

**Comment by Yongyao** [comment]
I tested the core with this data. It works well. Just a note, please use the data provided by @quintinali , and forget the data I put at the beginning of this thread.

Also, as the goal of this stage is to get it running on PO.DAAC, we can just stick with this processed data. The real-time ingesting/streaming has been put in the follow-on proposal.

**Comment by lewismc** [comment]
@Yongyao please don't use the data provided by @quintinali , use the most recent data provided by Chris Finch. He sent an email to the mudrod-all mailing list on December 7th, 2016. I've been working with this data. It can be found at ftp://podaac.jpl.nasa.gov/misc/outgoing/cjf/mudrod/

**Comment by fgreg** [comment]
Works.
