### ISSUE TITLE
Fail to run mudrod in windows system

### ISSUE THREAD

**Issue by quintinali** [mudrod/mudrod#91]
@lewismc I tried to run mudrod(https://github.com/mudrod/mudrod/tree/temp0907) in windows system with command: java -jar  mudrod-core-uber-0.0.1-SNAPSHOT.jar but failed, the prompted error is: 

com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'

Some people suggest using maven shade plugin to solve such problem, however, we already use this plugin in the pom.xml. Do you know how to solve it? Thanks for your help

**Comment by lewismc** [comment]
I'll look into it now @quintinali

**Comment by lewismc** [comment]
@quintinali can you please post the entire stack trace you see?

**Comment by lewismc** [comment]
Are you getting this issue with master branch?

**Comment by quintinali** [comment]
I use this branch: https://github.com/mudrod/mudrod/tree/temp0907  I will post the stack trace after I reinstall the jar package

**Comment by quintinali** [comment]
```
C:\Users\tinay\OneDrive\Documents\GitHub\mudrod\core\target>java -jar mudrod-core-uber-0.0.1-SNAPSHOT.jar -logDir E:\mudrod_test_data\Testing_Data_1_3dayLog+Meta+Onto -f
2017-02-09 15:02:22,531 INFO  elasticsearch.plugins (PluginsService.java:<init>(180)) - [Varnae] modules [], plugins [], sites []
                                                                                                               2017-02-09 15:02:23,931 WARN  util.NativeCodeLoader (NativeCodeLoader.java:<clinit>(62)) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-02-09 15:02:24,944 ERROR spark.SparkContext (Logging.scala:logError(95)) - Error initializing SparkContext.
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
        at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:169)
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
        at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:52)
        at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:2024)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
        at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:2015)
        at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:55)
        at org.apache.spark.SparkEnv$.create(SparkEnv.scala:266)
        at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
        at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:288)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
        at esiptestbed.mudrod.driver.SparkDriver.<init>(SparkDriver.java:34)
        at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:337)
usage: MudrodEngine: 'logDir' argument is mandatory. User must also
       provide either 'logIngest' or 'fullIngest'. [-a] [-f] [-h] [-l]
       -logDir <logDir> [-p] [-s] [-v]
 -a,--addSimFromMetadataAndOnto   begin adding metadata and ontology
                                  results
 -f,--fullIngest                  begin full ingest Mudrod workflow
 -h,--help                        show this help message
 -l,--logIngest                   begin log ingest without any processing
                                  only
 -logDir <logDir>                 the log directory to be processed by
                                  Mudrod
 -p,--processingWithPreResults    begin processing with preprocessing
                                  results
 -s,--sessionReconstruction       begin session reconstruction
 -v,--vocabSimFromLog             begin similarity calulation from web log
                                  Mudrod workflow
MudrodEngine: 'logDir' argument is mandatory. User must also provide either 'logIngest' or 'fullIngest'.
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
        at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:169)
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
        at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:52)
        at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:2024)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
        at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:2015)
        at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:55)
        at org.apache.spark.SparkEnv$.create(SparkEnv.scala:266)
        at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
        at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:288)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
        at esiptestbed.mudrod.driver.SparkDriver.<init>(SparkDriver.java:34)
        at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:337)
2017-02-09 15:02:24,963 ERROR main.MudrodEngine (MudrodEngine.java:main(369)) - MudrodEngine: 'logDir' argument is mandatory. User must also provide either 'logIngest' or 'fullIngest'.
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
        at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
        at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:169)
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:505)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:142)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:119)
        at org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:121)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:53)
        at org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:52)
        at org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:2024)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
        at org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:2015)
        at org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:55)
        at org.apache.spark.SparkEnv$.create(SparkEnv.scala:266)
        at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:193)
        at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:288)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:457)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
        at esiptestbed.mudrod.driver.SparkDriver.<init>(SparkDriver.java:34)
        at esiptestbed.mudrod.main.MudrodEngine.main(MudrodEngine.java:337)
```

**Comment by lewismc** [comment]
This issue is linked to #92

**Comment by quintinali** [comment]
Thanks. Ｉwill try it now

**Comment by quintinali** [comment]
@lewismc  The latest branch works well on the windows system. Thanks very much!
